apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: frontend-service
  name: {{ .Release.Name }}-frontend-svc
  namespace: kanban
spec:
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: {{ .Values.service.port }}
  selector:
    app: frontend
  type: {{ .Values.service.type }}
status:
  loadBalancer: {}

