version: "3.8"
services:
  reactapp:
    container_name: reactapp
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - REACT_APP_BACKEND_IP=192.168.56.28
    ports:
      - 3000:80
    networks:
      - back
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 2m

  nodeapp:
    container_name: nodeapp
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    networks:
      - back
    environment:
      - PORT=5000
      - PASSWORD_SECRET_KEY=changeme
      - TOKEN_SECRET_KEY=changeme
      - MONGODB_URL=mongodb://username:password@mongodb:27017/kanbanDB

networks:
  back:
   name: kanban-network
   external: true


    
