version: "3.8"
services:
  mongodb:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: test
    networks:
      - back
    volumes:
      - mongodb-data:/data/db

networks:
  back:
   name: kanban-network
   external: true

volumes:
  mongodb-data:
    external:
      name: kanban-volume