apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: kanban
spec:
  selector:
    matchLabels:
      app: mongodb
  serviceName: "mongo"
  replicas: 
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: mongodb 
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mongodb
        image: mongo:latest
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: admin
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-password
              key: password
        - name: MONGO_INITDB_DATABASE
          value: test
        command: ["mongod", " - replSet=rs0", " - bind_ip_all"]
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongo-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "local-path"
      resources:
        requests:
          storage: 1Gi